# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "About"
pageRef = "about"
weight = 3

[[main]]
name = "PG Mage"
pageRef = "pg"
weight = 4

[[main]]
name = "DB Guru"
pageRef = "db"
weight = 5

[[main]]
name = "Cloud-Exit"
pageRef = "cloud"
weight = 6

[[main]]
name = "Column"
weight = 10

[[main]]
  parent = "Column"
  name = "Database Guru"
  pageRef = "db"
  weight = 12

[[main]]
  parent = "Column"
  name = "Cloud-Exit Mudslide"
  pageRef = "cloud"
  weight = 13

[[main]]
  parent = "Column"
  name = "PostgreSQL Mage"
  pageRef = "pg"
  weight = 11

[[main]]
  parent = "Column"
  name = "Travel Notes"
  pageRef = "trip"
  weight = 14

[[main]]
  parent = "Column"
  name = "Miscellaneous"
  pageRef = "misc"
  weight = 15

[[main]]
name = "Portfolio"
weight = 50

[[main]]
name = "Pigsty, FOSS PG RDS"
parent = "Portfolio"
url = "https://pgsty.com"
weight = 51

[[main]]
name = "PGEXT CLOUD"
parent = "Portfolio"
url = "https://pgext.cloud"
weight = 60

[[main]]
name = "PG Exporter Agent"
parent = "Portfolio"
url = "https://exp.pgsty.com"
weight = 70

[[main]]
name = "Capslock Enhancement"
parent = "Portfolio"
url = "https://capslock.vonng.com"
weight = 80

[[main]]
name = "DDIA CN Translation"
parent = "Portfolio"
url = "https://ddia.vonng.com"
weight = 90

[[main]]
name = "PG Internal CN Translation"
parent = "Portfolio"
url = "https://pgint.vonng.com"
weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/RonVonng"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Vonng"
  weight = 400

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
