# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "关于"
pageRef = "about"
weight = 3

[[main]]
name = "PGSQL"
pageRef = "pg"
weight = 4

[[main]]
name = "云计算"
pageRef = "cloud"
weight = 5

[[main]]
name = "数据库"
pageRef = "db"
weight = 6


[[main]]
name = "专栏"
weight = 10

[[main]]
  parent = "专栏"
  name = "数据库老司机"
  pageRef = "db"
  weight = 11

[[main]]
  parent = "专栏"
  name = "云计算泥石流"
  pageRef = "cloud"
  weight = 12

[[main]]
  parent = "专栏"
  name = "PGSQL大法师"
  pageRef = "pg"
  weight = 13

[[main]]
  parent = "专栏"
  name = "行万里路"
  pageRef = "trip"
  weight = 14

[[main]]
  parent = "专栏"
  name = "闲言随笔"
  pageRef = "misc"
  weight = 15


[[main]]
  name = "作品"
  weight = 40

[[main]]
  name = "Pigsty, 开源 PG RDS"
  parent = "作品"
  url = "https://pgsty.com/zh/"
  weight = 50

[[main]]
  name = "PostgreSQL 扩展云"
  parent = "作品"
  url = "https://pgext.cloud/zh/"
  weight = 60

[[main]]
name = "PG Exporter 监控组件"
parent = "作品"
url = "https://exp.pgsty.com"
weight = 70

[[main]]
  name = "Capslock 修饰键改造"
  parent = "作品"
url = "https://capslock.vonng.com/zh"
  weight = 80

[[main]]
  name = "设计数据密集型应用"
  parent = "作品"
  url = "https://ddia.vonng.com"
  weight = 90

[[main]]
  name = "PostgreSQL 内幕探索"
  parent = "作品"
  url = "https://pgint.vonng.com"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/RonVonng"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Vonng"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "标签"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "作者"
   pageRef = "authors"
   weight = 20
